// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['jquery', 'libs/backbone', 'model/preloader', 'app/config', 'view/pageViewPC', 'view/pageViewMobile'], function($, _b, Preloader, Config, PageViewPC, PageViewMobile) {
  var AppState;
  return AppState = (function() {

    AppState.STATE_READY = 'STATE_READY';

    AppState.isTablet = /ipad|android 3|sch-i800|playbook|tablet|kindle|gt-p1000|sgh-t849|shw-m180s|a510|a511|a100|dell streak|silk/i.test(navigator.userAgent.toLowerCase());

    AppState.isMobile = /iphone|ipod|android|blackberry|opera mini|opera mobi|skyfire|maemo|windows phone|palm|iemobile|symbian|symbianos|fennec/i.test(navigator.userAgent.toLowerCase());

    AppState.isDesktop = false;

    function AppState() {
      this.setMobile = __bind(this.setMobile, this);

      this.setDesktop = __bind(this.setDesktop, this);

      this.start = __bind(this.start, this);
      _.extend(this, Backbone.Events);
    }

    AppState.prototype.start = function() {
      AppState.isDesktop = !AppState.isTablet && !AppState.isMobile;
      this.html = $('html');
      if (AppState.isMobile || AppState.isTablet) {
        this.setMobile();
      }
      if (AppState.isDesktop) {
        return this.setDesktop();
      }
    };

    AppState.prototype.setDesktop = function() {
      var ieVersion, test;
      this.html.addClass('desktop');
      this.pageView = new PageViewPC();
      if (/MSIE/.test(navigator.userAgent)) {
        $html.addClass('ie');
      }
      test = new RegExp("MSIE ([0-9]{1,}[\.0-9]{0,})");
      if (test.exec(navigator.userAgent)) {
        ieVersion = parseFloat(RegExp.$1);
        this.html.addClass('ie-' + ieVersion);
        if (ieVersion <= 8) {
          return this.html.addClass('old-ie');
        } else {
          return this.html.addClass('new-ie');
        }
      } else {
        return this.html.addClass('non-ie');
      }
    };

    AppState.prototype.setMobile = function() {
      return this.html.addClass('mobile');
    };

    return AppState;

  })();
});
